apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
       metadata:
      labels:
        app: myjavaapp
       
    spec:
     containers:
     - name: mycontainer
       image: maha4iac/mahaonlinestore:2
       ports:
        - containerPort: 8080